class TB_CM_CMUT_MEM {
    constructor(CMUT_NO,MEM_NO,CMUT_MEM_NM, CMUT_MEM_TITLE_NM,CMUT_MEM_PRF_IMG_PATH,
        CMUT_MEM_ST_CD, CMUT_ROLE_CD, REL_CMUT_YN, CMUT_MEM_JOIN_DTTM,
        CMUT_MEM_JOIN_MEM_NO, CMUT_MEM_AV_DTTM, CMUT_MEM_SECS_DTTM, CMUT_MEM_SECS_CN,
        FST_REG_DTTM, FST_REG_USID, LST_CH_DTTM, LST_CH_USID
        ){
        this.CMUT_NO = CMUT_NO;
        this.MEM_NO = MEM_NO;
        this.CMUT_MEM_NM = CMUT_MEM_NM;
        this.CMUT_MEM_TITLE_NM = CMUT_MEM_TITLE_NM;
        this.CMUT_MEM_PRF_IMG_PATH = CMUT_MEM_PRF_IMG_PATH;
        this.CMUT_MEM_ST_CD = CMUT_MEM_ST_CD;
        this.CMUT_ROLE_CD = CMUT_ROLE_CD;
        this.REL_CMUT_YN = REL_CMUT_YN;
        this.CMUT_MEM_JOIN_DTTM = CMUT_MEM_JOIN_DTTM;
        this.CMUT_MEM_JOIN_MEM_NO = CMUT_MEM_JOIN_MEM_NO;
        this.CMUT_MEM_AV_DTTM = CMUT_MEM_AV_DTTM;
        this.CMUT_MEM_SECS_DTTM = CMUT_MEM_SECS_DTTM;
        this.CMUT_MEM_SECS_CN = CMUT_MEM_SECS_CN;
        this.FST_REG_DTTM = FST_REG_DTTM;
        this.FST_REG_USID = FST_REG_USID;
        this.LST_CH_DTTM = LST_CH_DTTM;
        this.LST_CH_USID = LST_CH_USID;

    }
}

module.exports = TB_CM_CMUT_MEM